Repository Evarisk/dolimeet, pull requests merged in 2023-09, with the labels that each got.

#430 #429 [IHM] add: use picto in tabmenu on phone
  lib/dolimeet.lib.php
Labels: 1, Enhancement, IHM

#432 #431 [View] fix: fatal banner actions
  view/session/session_card.php
Labels: 1, Bug

#436 #433 [IHM] add: picto unlock
  view/session/session_card.php
Labels: 1, Enhancement, IHM

#441 #440 [Document] fix: inverted siret and declaration number
  documents/doctemplates/trainingsessiondocument/attendancesheetdocument/template_attendancesheetdocument.odt
Labels: 0, ODT
