Repository Evarisk/dolimeet, pull requests merged in 2023-07, with the labels that each got.

#342 #340 [Signature] fix: saturne interaction for modal
  public/signature/add_signature.php
Labels: 0, Enhancement

#345 #341 [TrainingSession] add: satisfaction survey
  admin/setup.php
  class/actions_dolimeet.class.php
  core/modules/modDoliMeet.class.php
  langs/fr_FR/dolimeet.lang
  view/session/session_card.php
Labels: 3, Enhancement

#361 #346 [CI/CD] add: editor config file for match PSR-12 conventions
  .editorconfig
Labels: 0, Enhancement

#364 #350 [JS/CSS] clean: unused CSS and JS
  css/dolimeet.min.css
  css/scss/style.scss
  gulpfile.js
  package-lock.json
  package.json
Labels: 1, Enhancement

#359 #353 [Triggers] clean: triggers file
  core/triggers/interface_99_modDoliMeet_DoliMeetTriggers.class.php
Labels: 1, Enhancement

#367 #354 [Mod] clean: mod files
  core/modules/dolimeet/dolimeetdocuments/attendancesheetdocument/index.php
  core/modules/dolimeet/dolimeetdocuments/attendancesheetdocument/mod_attendancesheetdocument_standard.php
  core/modules/dolimeet/dolimeetdocuments/completioncertificatedocument/index.php
  core/modules/dolimeet/dolimeetdocuments/completioncertificatedocument/mod_completioncertificatedocument_standard.php
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/mod_attendancesheetdocument_standard.php
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/mod_completioncertificatedocument_standard.php
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/modules_trainingsessiondocument.php
  core/modules/dolimeet/modules_dolimeet.php
  core/modules/dolimeet/session/mod_audit_standard.php
  core/modules/dolimeet/session/mod_meeting_standard.php
  core/modules/dolimeet/session/mod_trainingsession_standard.php
  core/modules/modDoliMeet.class.php
Labels: 2, Enhancement

#368 #348 [Lib] clean: lib files
  lib/dolimeet.lib.php
  lib/dolimeet_audit.lib.php
  lib/dolimeet_functions.lib.php
  lib/dolimeet_meeting.lib.php
  lib/dolimeet_session.lib.php
  lib/dolimeet_trainingsession.lib.php
Labels: 1, Enhancement

#382 #371 [Admin] clean: remove unused files
  admin/about.php
  admin/dolimeetdocuments.php
  admin/setup.php
  lib/dolimeet.lib.php
Labels: 2, Enhancement

#386 #372 [SQL] add: attendants entries dico
  sql/data.sql
Labels: 1, Data model, Enhancement

#388 #373 [Mod] add: move files for require saturne issue
  core/modules/dolimeet/audit/index.php
  core/modules/dolimeet/audit/mod_audit_standard.php
  core/modules/dolimeet/meeting/index.php
  core/modules/dolimeet/meeting/mod_meeting_standard.php
  core/modules/dolimeet/trainingsession/index.php
  core/modules/dolimeet/trainingsession/mod_trainingsession_standard.php
Labels: 1, Enhancement

#381 #374 [Mod] fix: trad rights
  core/modules/modDoliMeet.class.php
Labels: 1, Bug

#385 #375 [Hook] add: saturneAttendantsBackToCard for saturne attendants page
  class/actions_dolimeet.class.php
Labels: 1, Enhancement

#384 #376 [Session] add: getNomUrl
  class/session.class.php
Labels: 1, Enhancement

#387 #377 [Triggers] fix: fatal fetch and conflict dolibarr triggers
  core/triggers/interface_99_modDoliMeet_DoliMeetTriggers.class.php
Labels: 2, Bug

#383 #378 [ODT] fix: fatal generation
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/doc_attendancesheetdocument_odt.modules.php
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/doc_completioncertificatedocument_odt.modules.php
  view/session/session_card.php
Labels: 1, Bug, ODT

#380 #379 [Lib] fix: $moreParams['parentType']
  lib/dolimeet_audit.lib.php
  lib/dolimeet_meeting.lib.php
  lib/dolimeet_trainingsession.lib.php
Labels: 1, Bug
