Repository Evarisk/dolimeet, pull requests merged in 2023-08, with the labels that each got.

#396 #395 [Session] add: remove MAIN_DISABLE_PDF_AUTOUPDATE
  view/session/session_card.php
Labels: 0, Enhancement

#399 #398 [Session] add: hook saturneBuildDoc for builddoc completioncertificate document
  class/actions_dolimeet.class.php
  core/modules/modDoliMeet.class.php
  view/session/session_card.php
Labels: 2, Enhancement

#400 #316 [Session] add: default sortoder DESC field date_creation for session
  class/session.class.php
  view/session/session_list.php
Labels: 1, Enhancement

#402 #401 [Session] fix: GETPOST date error with error action
  view/session/session_card.php
Labels: 1, Bug

#404 #403 [Session] fix: getNomUrl
  class/session.class.php
Labels: 1, Bug

#405 #266 [Session] add: JS action on fk_soc and fk_project
  gulpfile.js
  js/dolimeet.js
  js/dolimeet.min.js
  js/index.php
  js/modules/index.php
  js/modules/session.js
  package.json
  view/session/session_card.php
Labels: 2, Enhancement

#406 #282 [Session] fix: session don't have category
  .gitignore
  view/session/session_list.php
Labels: 1, Bug

#407 #370 [Hook] add: tags functionnality session
  class/actions_dolimeet.class.php
Labels: 2, Enhancement

#411 #410 [Admin] add: remove document location conf and use mycompany_town
  admin/setup.php
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/doc_completioncertificatedocument_odt.modules.php
  langs/fr_FR/dolimeet.lang
Labels: 1, Enhancement

#413 #412 [Session] add: parameter addLabel getNomUrl
  class/session.class.php
Labels: 1, Enhancement

#418 #417 [Session] fix: move parameter in function getNomUrl
  class/session.class.php
Labels: 0, Bug

#419 #409 [Session] fix: timezone & refresh bugs
  js/dolimeet.min.js
  js/modules/session.js
  view/session/session_card.php
  view/session/session_list.php
Labels: 2, Bug

#422 #421 [Class] fix: remove typage on $ismultientitymanaged
  class/dolimeetdocuments/attendancesheetdocument.class.php
  class/dolimeetdocuments/completioncertificatedocument.class.php
  class/session.class.php
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/doc_attendancesheetdocument_odt.modules.php
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/doc_completioncertificatedocument_odt.modules.php
Labels: 1, Bug

#425 #424 [Hook] fix: change hook for prevents conflict with other module
  class/actions_dolimeet.class.php
  core/modules/modDoliMeet.class.php
Labels: 1, Bug
