Repository Evarisk/dolimeet, pull requests merged in 2023-12, with the labels that each got.

#444 #443 [Document] add: trainer table in document
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/doc_attendancesheetdocument_odt.modules.php
  documents/doctemplates/trainingsessiondocument/attendancesheetdocument/template_attendancesheetdocument.odt
Labels: 1, Enhancement

#455 #454 [Hook] fix: Hook name
  class/actions_dolimeet.class.php
Labels: 0, Bug

#458 #457 [Mod] add: modAgenda dependancies
  core/modules/modDoliMeet.class.php
Labels: 0, Bug

#468 #467 [ODT] add: multipleAttendantsSegment more param for manage segment
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/doc_attendancesheetdocument_odt.modules.php
Labels: 0, Enhancement, ODT

#466 #463 [Session] fix: button validate displayed when no attendants
  view/session/session_card.php
Labels: 0, Bug

#462 #459 [Session] fix: apply model and retrieve all necessary documents
  view/session/session_card.php
Labels: 2, Bug

#469 #447 [Hook] add: special hook category for dolimeet
  class/actions_dolimeet.class.php
Labels: 1, Bug

#470 #434 [Session] fix: .php missing in the href
  view/session/session_card.php
Labels: 0, Bug

#461 #460 [Mod] add: new version number 1.2.1
  README.md
  core/modules/modDoliMeet.class.php
  core/triggers/interface_99_modDoliMeet_DoliMeetTriggers.class.php
Labels: 0, Enhancement

#472 #471 [Session] fix: better forcebuild doc
  view/session/session_card.php
Labels: 0, Bug

#480 #479 [Session] add: mail template contract convention
  core/modules/modDoliMeet.class.php
  core/substitutions/functions_dolimeet.lib.php
  core/substitutions/index.php
  langs/en_US/dolimeet.lang
  langs/fr_FR/dolimeet.lang
  sql/data.sql
Labels: 3, Enhancement

#485 #474 [Session] add: saturneBannerTab functionnal change with moreParams
  class/actions_dolimeet.class.php
  core/modules/modDoliMeet.class.php
  langs/en_US/dolimeet.lang
  langs/fr_FR/dolimeet.lang
Labels: 2, Bug

#489 #475 [Admin/Trigger/Hook] add: satisfaction survey
  admin/setup.php
  class/actions_dolimeet.class.php
  core/triggers/interface_99_modDoliMeet_DoliMeetTriggers.class.php
  langs/en_US/dolimeet.lang
  langs/fr_FR/dolimeet.lang
  lib/dolimeet_function.lib.php
Labels: 5, Enhancement

#487 #486 [Session] add: improve IHM session and signatory infos
  class/session.class.php
  langs/en_US/dolimeet.lang
  langs/fr_FR/dolimeet.lang
  view/session/session_list.php
Labels: 5, Enhancement, IHM

#488 #473 [Hook] add: use completeTabsHead hook for add nb sessions count
  class/actions_dolimeet.class.php
  core/modules/modDoliMeet.class.php
Labels: 2, Enhancement
