Repository Evarisk/dolimeet, pull requests merged in 2024-08, with the labels that each got.

#603 #580 [Dashboard] fix: show content if 0
  class/session.class.php
  langs/fr_FR/dolimeet.lang
Labels: 1, Bug

#610 #609 [Session] add: null content available
  class/session.class.php
Labels: 0, Enhancement

#608 #588 [Hook] add: custom message
  class/actions_dolimeet.class.php
  core/modules/modDoliMeet.class.php
  langs/fr_FR/dolimeet.lang
Labels: 3, Enhancement

#607 #596 [Mod] add: add email model for completion certificate
  core/modules/modDoliMeet.class.php
  langs/fr_FR/dolimeet.lang
Labels: 3, Enhancement

#628 #592 [Trad] add: charte mail
  langs/fr_FR/dolimeet.lang
Labels: 0, Enhancement, Translation

#629 #591 [Mod] add: remove joinfiles on mail
  core/modules/modDoliMeet.class.php
  sql/data.sql
  sql/update.sql
Labels: 2, Enhancement

#641 #632 [Session] fix: fk_element type integer:service
  view/session/session_list.php
Labels: 1, Bug

#642 #638 [Hook] add: trainee info
  class/actions_dolimeet.class.php
  core/modules/modDoliMeet.class.php
  langs/fr_FR/dolimeet.lang
  lib/dolimeet_function.lib.php
Labels: 2, Enhancement

#643 #636 [Hook] fix: hook name change in 19 contractcontactcard
  class/actions_dolimeet.class.php
Labels: 0, Bug
