Repository Evarisk/dolimeet, pull requests merged in 2024-01, with the labels that each got.

#491 #490 [Session] fix: get categories selected on edit action
  view/session/session_card.php
Labels: 1, Bug

#493 #492 [Hook] fix: conflict with currentcontext if globalcard enabled
  class/actions_dolimeet.class.php
Labels: 1, Bug

#497 #496 [Lib] fix: third argument of complete_subst_array mustnt be typed
  core/substitutions/functions_dolimeet.lib.php
Labels: 0, Bug

#507 #502 [Session] fix: backtolist fromtype if access to an object from type
  view/session/session_card.php
  view/session/session_list.php
Labels: 3, Bug

#515 #508 [Contract] add: generate completion certificate from contracts
  class/actions_dolimeet.class.php
  core/modules/modDoliMeet.class.php
Labels: 3, Enhancement

#513 #512 [Hook] add: check consistency of course dates
  class/actions_dolimeet.class.php
  langs/en_US/dolimeet.lang
  langs/fr_FR/dolimeet.lang
Labels: 2, Enhancement

#495 #475 [Hook] fix: algorithm performance and improve and add new contact type for satisfaction survey
  admin/setup.php
  class/actions_dolimeet.class.php
  core/triggers/interface_99_modDoliMeet_DoliMeetTriggers.class.php
  langs/en_US/dolimeet.lang
  langs/fr_FR/dolimeet.lang
  lib/dolimeet_function.lib.php
  sql/data.sql
  view/session/session_card.php
  view/session/session_list.php
Labels: 5, Enhancement

#517 #516 [TrainingSession] add: check if SESSION_TRAINER_RESPONSIBLE defined
  class/actions_dolimeet.class.php
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/doc_completioncertificatedocument_odt.modules.php
  langs/en_US/dolimeet.lang
  langs/fr_FR/dolimeet.lang
  view/session/session_card.php
Labels: 1, Enhancement

#519 #508 [Document] add: format
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/doc_completioncertificatedocument_odt.modules.php
Labels: 0, Enhancement

#521 #509 [Hook] add: training session durations info on contract
  class/actions_dolimeet.class.php
  langs/en_US/dolimeet.lang
  langs/fr_FR/dolimeet.lang
Labels: 1, Enhancement

#522 #514 [Mod] add: new version number 1.3.0
  README.md
  core/modules/modDoliMeet.class.php
  core/triggers/interface_99_modDoliMeet_DoliMeetTriggers.class.php
Labels: 0, Enhancement
