Repository Evarisk/dolimeet, pull requests merged in 2024-03, with the labels that each got.

#530 #529 [Trigger] fix: check version error
  core/triggers/interface_99_modDoliMeet_DoliMeetTriggers.class.php
Labels: 1, Bug

#534 #527 [Hook] fix: dont generate certificate for absent
  class/actions_dolimeet.class.php
  langs/en_US/dolimeet.lang
  langs/fr_FR/dolimeet.lang
Labels: 5, Bug

#540 #506 [Mod] add: email template for satisfaction survey
  core/modules/modDoliMeet.class.php
  core/substitutions/functions_dolimeet.lib.php
  langs/fr_FR/dolimeet.lang
Labels: 3, Enhancement

#545 #541 [Admin] add: check sheet type before select
  admin/setup.php
  langs/fr_FR/dolimeet.lang
Labels: 1, Enhancement

#544 #543 [Hook] fix: extendSheetLinkableObjectsList missing require lib file
  class/actions_dolimeet.class.php
Labels: 1, Bug

#532 #531 [Session] fix: navigation between objects fromType
  view/session/session_list.php
Labels: 1, Enhancement

#549 #548 [Hook] add: missing trad for link
  class/actions_dolimeet.class.php
Labels: 0, Enhancement

#551 #550 [Module] fix: remove useless file
  core/modules/dolimeet/dolimeetdocuments/trainingsessiondocument/modules_trainingsessiondocument.php
Labels: 0, Enhancement

#533 #524 [Hook] add: picto and tooltips before trainingsession contract extrafields
  class/actions_dolimeet.class.php
  core/modules/modDoliMeet.class.php
  langs/en_US/dolimeet.lang
  langs/fr_FR/dolimeet.lang
Labels: 3, Enhancement

#547 #546 [Mod] add: new version number 1.4.0
  README.md
  core/modules/modDoliMeet.class.php
  core/triggers/interface_99_modDoliMeet_DoliMeetTriggers.class.php
Labels: 0, Enhancement
