Repository Evarisk/dolimeet, pull requests merged in 2024-11, with the labels that each got.

#676 #675 [ActionDolimeet] fix: replace ref by label
  class/actions_dolimeet.class.php
Labels: 0, Enhancement

#671 #670 [Lib] add: FOR_ADM_GP1 service
  admin/setup.php
  core/triggers/interface_99_modDoliMeet_DoliMeetTriggers.class.php
  langs/fr_FR/dolimeet.lang
  lib/dolimeet_function.lib.php
  view/session/session_card.php
Labels: 1, Enhancement

#672 #654 [Mod] fix: remove billing contract type
  admin/setup.php
  class/actions_dolimeet.class.php
  core/modules/modDoliMeet.class.php
  core/triggers/interface_99_modDoliMeet_DoliMeetTriggers.class.php
  langs/en_US/dolimeet.lang
  langs/fr_FR/dolimeet.lang
Labels: 1, Bug
